import pytest

from apps.billing.models import Invoice, InvoiceLine, Payment, Quote, QuoteLine
from apps.customers.models import Customer


@pytest.fixture
def customer(db):
    return Customer.objects.create(name="Cliente Billing")


@pytest.mark.django_db
def test_quote_number_autogenerated(customer):
    q1 = Quote.objects.create(customer=customer)
    q2 = Quote.objects.create(customer=customer)
    assert q1.quote_number == f"COT-{q1.pk:06d}"
    assert q1.quote_number != q2.quote_number


@pytest.mark.django_db
def test_invoice_number_autogenerated_and_defaults(customer):
    inv = Invoice.objects.create(customer=customer)
    assert inv.invoice_number == f"FAC-{inv.pk:06d}"
    assert inv.status == Invoice.Status.DRAFT
    assert inv.invoice_type == Invoice.InvoiceType.SERVICE


@pytest.mark.django_db
def test_cascade_quote_lines(customer):
    q = Quote.objects.create(customer=customer)
    QuoteLine.objects.create(quote=q, description="X", quantity=1, unit_price=10)
    qid = q.id
    q.delete()
    assert not QuoteLine.objects.filter(quote_id=qid).exists()


@pytest.mark.django_db
def test_cascade_invoice_lines_and_payments(customer):
    inv = Invoice.objects.create(customer=customer)
    InvoiceLine.objects.create(invoice=inv, description="X", quantity=1, unit_price=10)
    Payment.objects.create(invoice=inv, amount=5)
    iid = inv.id
    inv.delete()
    assert not InvoiceLine.objects.filter(invoice_id=iid).exists()
    assert not Payment.objects.filter(invoice_id=iid).exists()
