# Generated by Django 5.1.4 on 2026-06-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_main_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase_in', 'Entrada por compra'), ('service_out', 'Salida por servicio'), ('sale_out', 'Salida por venta'), ('reservation', 'Reserva'), ('reservation_release', 'Liberación de reserva'), ('adjustment_in', 'Ajuste positivo'), ('adjustment_out', 'Ajuste negativo'), ('return_in', 'Devolución'), ('damaged_out', 'Baja por daño')], max_length=30),
        ),
    ]
