# Generated by Django 5.1.4 on 2026-06-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorymovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='default_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
