# Generated by Django 5.1.4 on 2026-07-28 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipmentcomponent'),
        ('inventory', '0005_productcategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_compatibilities', to='equipment.equipmentcomponent')),
                ('equipment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_compatibilities', to='equipment.equipmentmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='inventory.product')),
            ],
            options={
                'verbose_name_plural': 'Product compatibilities',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['product'], name='inventory_p_product_6ce12f_idx'), models.Index(fields=['equipment_model'], name='inventory_p_equipme_9c96c8_idx'), models.Index(fields=['component'], name='inventory_p_compone_116d7a_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'equipment_model', 'component'), name='uniq_product_model_component')],
            },
        ),
    ]
