# Generated by Django 5.1.4 on 2026-09-11 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_max_margin_percentage_product_max_sale_price_and_more'),
        ('purchasing', '0002_remove_purchaseorderline_calculated_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='average_cost_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='purchasing.purchaseorderline'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
