import pytest
from decimal import Decimal

from apps.customers.models import Customer
from apps.field_jobs.models import FieldJob

pytestmark = pytest.mark.django_db


def _customer():
    return Customer.objects.create(name="Finca La Esperanza")


def test_number_autogenerated_on_save():
    job = FieldJob.objects.create(customer=_customer())
    assert job.number == f"TC-{job.pk:06d}"


def test_defaults_fumigation_rice_one_hectare():
    job = FieldJob.objects.create(customer=_customer())
    assert job.job_type == FieldJob.JobType.FUMIGATION
    assert job.status == FieldJob.Status.SCHEDULED
    assert job.crop == FieldJob.Crop.RICE
    assert job.hectares == Decimal("1")


def test_recalculate_total_is_hectares_times_price():
    job = FieldJob.objects.create(
        customer=_customer(), hectares=Decimal("15"), unit_price=Decimal("20")
    )
    job.recalculate_total()
    assert job.total == Decimal("300.00")


def test_crop_other_stores_free_text():
    job = FieldJob.objects.create(
        customer=_customer(), crop=FieldJob.Crop.OTHER, crop_other="Sandía"
    )
    assert job.get_crop_display() == "Otros"
    assert job.crop_other == "Sandía"
