from decimal import Decimal

import pytest

from apps.customers.models import Customer
from apps.field_jobs.models import FieldJob


@pytest.mark.django_db
def test_number_autogenerated():
    job = FieldJob.objects.create(customer=Customer.objects.create(name="C1"))
    assert job.number == f"TC-{job.pk:06d}"


@pytest.mark.django_db
def test_recalculate_total_fumigation_uses_hectares():
    job = FieldJob(
        customer=Customer.objects.create(name="C2"),
        job_type=FieldJob.JobType.FUMIGATION,
        hectares=Decimal("12.5"),
        quintals=Decimal("99"),
        unit_price=Decimal("20"),
    )
    job.recalculate_total()
    assert job.total == Decimal("250.0000")  # 12.5 * 20; quintals ignorado


@pytest.mark.django_db
def test_recalculate_total_spreading_uses_quintals():
    job = FieldJob(
        customer=Customer.objects.create(name="C3"),
        job_type=FieldJob.JobType.SPREADING,
        hectares=Decimal("99"),
        quintals=Decimal("8"),
        unit_price=Decimal("10"),
    )
    job.recalculate_total()
    assert job.total == Decimal("80.0000")  # 8 * 10; hectares ignorado


@pytest.mark.django_db
def test_ordering_recent_scheduled_first():
    from datetime import date

    c = Customer.objects.create(name="C4")
    old = FieldJob.objects.create(customer=c, scheduled_date=date(2026, 1, 1))
    new = FieldJob.objects.create(customer=c, scheduled_date=date(2026, 6, 1))
    ids = list(FieldJob.objects.values_list("id", flat=True))
    assert ids.index(new.id) < ids.index(old.id)
