# Generated by Django 5.1.4 on 2026-06-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('general_admin', 'Administrador General'), ('sales', 'Facturación / Ventas'), ('technician', 'Técnico'), ('inventory', 'Inventario'), ('accounting', 'Contabilidad'), ('readonly', 'Consulta')], default='technician', max_length=20),
        ),
    ]
