# Generated by Django 5.1.4 on 2026-06-03 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('equipment', '0002_seed_equipment_types'),
        ('inventory', '0002_product_main_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_order_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('service_type', models.CharField(choices=[('diagnostic', 'Diagnóstico'), ('preventive_maintenance', 'Mantenimiento preventivo'), ('corrective_maintenance', 'Mantenimiento correctivo'), ('repair', 'Reparación'), ('cleaning', 'Limpieza'), ('calibration', 'Calibración'), ('other', 'Otro')], default='diagnostic', max_length=30)),
                ('status', models.CharField(choices=[('received', 'Recibida'), ('in_diagnostic', 'En diagnóstico'), ('quoted', 'Cotizada'), ('approved', 'Aprobada'), ('in_progress', 'En proceso'), ('waiting_parts', 'Esperando piezas'), ('finished', 'Finalizada'), ('invoiced', 'Facturada'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada')], default='received', max_length=30)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('customer_complaint', models.TextField(blank=True)),
                ('diagnostic_summary', models.TextField(blank=True)),
                ('technical_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diagnostic_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='customers.customer')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='equipment.equipment')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders_as_technician', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('required', 'Requerida'), ('reserved', 'Reservada'), ('used', 'Usada'), ('pending_purchase', 'Pendiente de compra'), ('returned', 'Devuelta')], default='required', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_parts', to='inventory.product')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='service_orders.serviceorder')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
