# Generated by Django 5.1.4 on 2026-07-28 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipmentcomponent'),
        ('service_orders', '0003_serviceorder_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderpart',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_order_parts', to='equipment.equipmentcomponent'),
        ),
    ]
