# Generated by Django 5.1.4 on 2026-06-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='default_water_per_hectare',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=8),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='drone_tank_volume_liters',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=8),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='fumigation_price_per_hectare',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='spreading_price_per_quintal',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
