# Generated by Django 5.1.4 on 2026-06-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyprofile_default_water_per_hectare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='drone_tank_volume_liters',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=8),
        ),
    ]
