# Generated by Django 5.1.4 on 2026-07-28 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_seed_equipment_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('model_code', models.CharField(max_length=100)),
                ('revision', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('diagram_type', models.CharField(choices=[('svg', 'SVG'), ('image', 'Imagen')], default='svg', max_length=20)),
                ('diagram_file', models.FileField(blank=True, null=True, upload_to='equipment_models/diagrams/')),
                ('is_active', models.BooleanField(default=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_models', to='equipment.equipmenttype')),
            ],
            options={
                'ordering': ('brand', 'name'),
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='catalog_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_units', to='equipment.equipmentmodel'),
        ),
        migrations.AddConstraint(
            model_name='equipmentmodel',
            constraint=models.UniqueConstraint(fields=('brand', 'model_code', 'revision'), name='uniq_equipment_model_brand_code_rev'),
        ),
    ]
