# Generated by Django 5.1.4 on 2026-07-28 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipmentmodel_equipment_catalog_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('component_type', models.CharField(choices=[('assembly', 'Conjunto'), ('position', 'Posición reemplazable')], default='position', max_length=20)),
                ('diagram_key', models.CharField(blank=True, default='', max_length=100)),
                ('position', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='equipment.equipmentmodel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='equipment.equipmentcomponent')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'indexes': [models.Index(fields=['equipment_model'], name='equipment_e_equipme_65efc8_idx'), models.Index(fields=['parent'], name='equipment_e_parent__0abfdc_idx')],
                'constraints': [models.UniqueConstraint(fields=('equipment_model', 'code'), name='uniq_component_model_code')],
            },
        ),
    ]
