# Generated by Django 5.1.4 on 2026-06-23 14:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_invoice_field_job_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cufe', models.CharField(max_length=120)),
                ('protocol', models.CharField(blank=True, max_length=60)),
                ('fiscal_status', models.CharField(choices=[('pending', 'Pendiente'), ('authorized', 'Autorizada'), ('rejected', 'Rechazada'), ('cancelled', 'Anulada')], default='authorized', max_length=20)),
                ('environment', models.CharField(choices=[('demo', 'Demo / Pruebas'), ('production', 'Producción')], default='demo', max_length=20)),
                ('provider', models.CharField(default='demo', max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal', to='billing.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
