# Generated by Django 5.1.4 on 2026-06-19 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_discount_percentage_invoice_tax_percentage_and_more'),
        ('field_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='field_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='field_jobs.fieldjob'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('service_invoice', 'Factura de servicio'), ('final_invoice', 'Factura final'), ('product_sale', 'Venta de producto'), ('field_job', 'Factura de fumigación')], default='service_invoice', max_length=20),
        ),
    ]
