# Generated by Django 5.1.4 on 2026-06-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='calculated_sale_price',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='final_sale_price',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='margin_percentage',
        ),
    ]
