import pytest

from apps.inventory.models import Product
from apps.purchasing.models import (
    PurchaseAdditionalCost,
    PurchaseOrder,
    PurchaseOrderLine,
)
from apps.suppliers.models import Supplier


@pytest.fixture
def supplier(db):
    return Supplier.objects.create(name="Proveedor X")


@pytest.mark.django_db
def test_order_number_autogenerated_and_unique(supplier):
    o1 = PurchaseOrder.objects.create(supplier=supplier)
    o2 = PurchaseOrder.objects.create(supplier=supplier)
    assert o1.order_number == f"OC-{o1.pk:06d}"
    assert o2.order_number == f"OC-{o2.pk:06d}"
    assert o1.order_number != o2.order_number


@pytest.mark.django_db
def test_order_number_respected_if_given(supplier):
    o = PurchaseOrder.objects.create(supplier=supplier, order_number="OC-CUSTOM")
    assert o.order_number == "OC-CUSTOM"


@pytest.mark.django_db
def test_status_default_draft(supplier):
    o = PurchaseOrder.objects.create(supplier=supplier)
    assert o.status == PurchaseOrder.Status.DRAFT


@pytest.mark.django_db
def test_cascade_lines_and_costs(supplier):
    product = Product.objects.create(sku="P-1", name="Pieza")
    order = PurchaseOrder.objects.create(supplier=supplier)
    PurchaseOrderLine.objects.create(
        purchase_order=order, product=product, quantity_ordered=1, unit_purchase_cost=10
    )
    PurchaseAdditionalCost.objects.create(purchase_order=order, name="Envío", amount=5)
    order_id = order.id
    order.delete()
    assert not PurchaseOrderLine.objects.filter(purchase_order_id=order_id).exists()
    assert not PurchaseAdditionalCost.objects.filter(
        purchase_order_id=order_id
    ).exists()
