import pytest

from apps.customers.models import Customer
from apps.inventory.models import Product
from apps.service_orders.models import ServiceOrder, ServiceOrderPart


@pytest.fixture
def customer(db):
    return Customer.objects.create(name="Cliente X")


@pytest.mark.django_db
def test_service_order_number_autogenerated_and_unique(customer):
    o1 = ServiceOrder.objects.create(customer=customer)
    o2 = ServiceOrder.objects.create(customer=customer)
    assert o1.service_order_number == f"OS-{o1.pk:06d}"
    assert o2.service_order_number == f"OS-{o2.pk:06d}"
    assert o1.service_order_number != o2.service_order_number


@pytest.mark.django_db
def test_status_and_type_defaults(customer):
    o = ServiceOrder.objects.create(customer=customer)
    assert o.status == ServiceOrder.Status.RECEIVED
    assert o.service_type == ServiceOrder.ServiceType.DIAGNOSTIC


@pytest.mark.django_db
def test_cascade_parts(customer):
    product = Product.objects.create(sku="SP-1", name="Pieza")
    order = ServiceOrder.objects.create(customer=customer)
    ServiceOrderPart.objects.create(
        service_order=order, product=product, quantity=1
    )
    order_id = order.id
    order.delete()
    assert not ServiceOrderPart.objects.filter(service_order_id=order_id).exists()


@pytest.mark.django_db
def test_part_default_status_required(customer):
    product = Product.objects.create(sku="SP-2", name="Pieza")
    order = ServiceOrder.objects.create(customer=customer)
    part = ServiceOrderPart.objects.create(
        service_order=order, product=product, quantity=2
    )
    assert part.status == ServiceOrderPart.Status.REQUIRED
