# Generated by Django 5.1.4 on 2026-06-19 03:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('equipment', '0002_seed_equipment_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=30, unique=True)),
                ('job_type', models.CharField(choices=[('fumigation', 'Fumigación'), ('spreading', 'Esparcido / abono')], default='fumigation', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('done', 'Hecho'), ('invoiced', 'Facturado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateField(default=django.utils.timezone.localdate)),
                ('done_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('crop', models.CharField(blank=True, max_length=100)),
                ('applied_product', models.CharField(blank=True, max_length=255)),
                ('hectares', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('quintals', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('application_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('application_rate_unit', models.CharField(blank=True, choices=[('L/ha', 'L/ha'), ('mL/ha', 'mL/ha'), ('kg/ha', 'kg/ha'), ('cc/ha', 'cc/ha')], max_length=10)),
                ('tank_volume_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('water_per_hectare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('wind_speed_kmh', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('humidity_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weather_notes', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_jobs', to='customers.customer')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_jobs', to='equipment.equipment')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-scheduled_date', '-created_at'),
            },
        ),
    ]
