# Generated by Django 5.1.4 on 2026-06-21 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldJobProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('dose_per_hectare', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('unit', models.CharField(choices=[('L/ha', 'L/ha'), ('mL/ha', 'mL/ha'), ('cc/ha', 'cc/ha'), ('kg/ha', 'kg/ha'), ('g/ha', 'g/ha')], default='L/ha', max_length=10)),
                ('field_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='field_jobs.fieldjob')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
