# Generated by Django 5.1.4 on 2026-06-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_jobs', '0002_fieldjobproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldjob',
            name='application_rate',
        ),
        migrations.RemoveField(
            model_name='fieldjob',
            name='application_rate_unit',
        ),
        migrations.RemoveField(
            model_name='fieldjob',
            name='applied_product',
        ),
        migrations.RemoveField(
            model_name='fieldjob',
            name='humidity_percentage',
        ),
        migrations.RemoveField(
            model_name='fieldjob',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='fieldjob',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='fieldjob',
            name='quintals',
        ),
        migrations.RemoveField(
            model_name='fieldjob',
            name='temperature_celsius',
        ),
        migrations.RemoveField(
            model_name='fieldjob',
            name='weather_notes',
        ),
        migrations.RemoveField(
            model_name='fieldjob',
            name='wind_speed_kmh',
        ),
        migrations.AddField(
            model_name='fieldjob',
            name='crop_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fieldjob',
            name='crop',
            field=models.CharField(choices=[('rice', 'Arroz'), ('corn', 'Maíz'), ('pasture', 'Pasto'), ('other', 'Otros')], default='rice', max_length=20),
        ),
        migrations.AlterField(
            model_name='fieldjob',
            name='hectares',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
    ]
