# Generated by Django 5.1.4 on 2026-09-15 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('field_jobs', '0003_remove_fieldjob_application_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('hectares', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('crop', models.CharField(choices=[('rice', 'Arroz'), ('corn', 'Maíz'), ('pasture', 'Pasto'), ('other', 'Otros')], default='rice', max_length=20)),
                ('crop_other', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('water_per_hectare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plots', to='customers.customer')),
            ],
            options={
                'ordering': ('customer', 'name'),
            },
        ),
        migrations.AddField(
            model_name='fieldjob',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_jobs', to='field_jobs.fieldplot'),
        ),
        migrations.CreateModel(
            name='FieldPlotProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('dose_per_hectare', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('unit', models.CharField(choices=[('L/ha', 'L/ha'), ('cc/ha', 'cc/ha'), ('kg/ha', 'kg/ha'), ('g/ha', 'g/ha')], default='L/ha', max_length=10)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='field_jobs.fieldplot')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='fieldplot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('customer', 'name'), name='uniq_active_plot_name_per_customer'),
        ),
    ]
